# Generated by Django 4.2.8 on 2024-01-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('sprite', models.URLField()),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(max_length=100)),
                ('game', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('caught', models.BooleanField()),
                ('dexNo', models.IntegerField()),
            ],
        ),
    ]
