# Generated by Django 4.2.8 on 2024-01-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0003_alter_pokemon_dexno_alter_pokemon_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
