# Generated by Django 4.2.8 on 2024-01-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0004_alter_pokemon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='sprite',
            field=models.CharField(max_length=100),
        ),
    ]
